#!/usr/bin/env ruby
# frozen_string_literal: true

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

unshift_path = ->(path) {
  p = File.expand_path("../../#{path}", __FILE__)
  $LOAD_PATH.unshift(p) unless $LOAD_PATH.include?(p)
}
unshift_path.call("lib")

require "bundler/setup"
require "roast"

puts "🔥🔥🔥 Everyone loves a good roast 🔥🔥🔥\n\n"
Roast::CLI.start(ARGV)
