#!/usr/bin/env ruby
# frozen_string_literal: true

if ARGV.length != 2
  puts "Usage: #{File.basename($PROGRAM_NAME)} SUBJECT_FILE TEST_FILE"
  exit 1
end

subject_file, test_file = ARGV

def detect_package_manager
  return "pnpm" if File.exist?(File.join(Dir.pwd, "pnpm-lock.yaml"))
  return "yarn" if File.exist?(File.join(Dir.pwd, "yarn.lock"))

  "npm"
end

jest_options = [
  "--verbose",
  "--no-colors",
  "--ci",
  "--coverageReporters=text-summary",
  "--collectCoverageFrom=#{subject_file}",
]

# Assumes the test command is `test:coverage`
# Both admin-web and checkout-web use this command
command = "#{detect_package_manager} run test:coverage -- #{test_file} #{jest_options.join(" ")}"

$stderr.puts "Running: #{command}"
puts system(command)
