#!/usr/bin/env ruby
# frozen_string_literal: true

require "rubygems"
require "bundler/setup"

require_relative "../../lib/roast/helpers/minitest_coverage_runner"

# Suppress fancy minitest reporting
ENV["RM_INFO"] = "true"

if ARGV.length != 2
  puts "Usage: #{File.basename($PROGRAM_NAME)} SUBJECT_FILE TEST_FILE"
  exit 1
end

test_file, subject_file = ARGV

Roast::Helpers::MinitestCoverageRunner.new(test_file, subject_file).run
